### PR TITLE
Add unique anchor for duplicate headline linking in PPP

### PR DESCRIPTION
**Pull request by AlWo223**

### CODE REVIEW

**Review by skylee03 — APPROVED** [review]
LGTM!

**Comment by skylee03** [comment]
> LGTM!

But I think the correct anchor should be `#activity-management`.

**Comment by AlWo223** [comment]
> > LGTM!
> 
> But I think the correct anchor should be `#activity-management`.

There are two activity-management headlines in UG and DG, I am trying to reference the first one of each document. But I have no idea whether this works

**Comment by skylee03** [comment]
> > > LGTM!
> > 
> > 
> > But I think the correct anchor should be `#activity-management`.
> 
> There are two activity-management headlines in UG and DG, I am trying to reference the first one of each document. But I have no idea whether this works

I tried but this did not work.

**Comment by skylee03** [comment]
You can specify the HTML id using the [syntax of kramdown](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id).

**Comment by AlWo223** [comment]
Just inspected the html docs and realised there are no duplicates 🙃 For DG the relevant section is actually called activity-management-in-AtheltiCLI and in UG there is a "-" placeholder for emoji included. This should fix it

**Pull request merged**
