### PR TITLE
Convert fats to fat

### LINKED ISSUE #319: Standardisation Issue: "Fats" used in Diet Goal and "Fat" in Diet
Initially I choose `fat` because `protein`, `carb` were in singular form as well. Should we use `fat` everywhere to be consistent?

### PR DESCRIPTION
**Pull request by yicheng-toh**
As requested by Nihal
You should not find the word 'fats' in the project.
Fixes #319

### CODE REVIEW

**Review by nihalzp — APPROVED** [review]
Thank you very much for taking the time and effort to change it. LGTM!

**Comment by yicheng-toh** [comment]
However, it failed one test case, how can I rectify it?

**Comment by nihalzp** [comment]
> However, it failed one test case, how can I rectify it?

Seems like one of my function's test case failed. Merge it; I will fix it in my upcoming PR.

**Review by skylee03 — APPROVED** [review]
LGTM!

**Pull request merged**
